### PR TITLE
Fixing arguments passed to do_test_actual

### LINKED ISSUE #29: iozone command line options aren't being set when using fsync and mmap in throughput mode
Description:
When running in throughput mode with --syncedincache or --mmapincache the iozone command should include the necessary -e and -B for fsync and mmap respectively, and neither for the simple --incache subtest.  The command line used for throughput mode is hard coded to use -e in all cases:

From do_test_actual:
time taskset -c 0  ${iozone_exe} -t $4 -i ${6} -+n -r ${page_size} -s${file_size}g -e -c -w -C ${iozone_args} -F ${5} >> ${iozone_output_file}

From an output file from a test run:
Command line used: /usr/bin/iozone -t 2 -i 0 -+n -r 1024 -s5g -e -c -w -C -F //iozone/iozone00/file_1 //iozone/iozone01/file_1

Expected behavior:
-e, -B, or nothing should be set according to the subtest being run

Actual behavior:
All -e (fysnc) all the time

### LINKED ISSUE #30: iozone command line options aren't being set in auto mode due to spaces in passed arguments
In auto mode, in execute_test spaces in the arguments passed to do_test are getting interpreted as separate entities, causing the final iozone command line to be incorrect. For example:

do_test "In Cache w/ MMAP" "incache+mmap" "-n ${page_size}k -g ${incache_maxfile}m -y 1k -q 1m -B" 

is generating a final command line of:

/usr/bin/iozone -az -f /iozone/iozone0/iozone-xfs w/ /iozone/iozone/iozone1

Through experimentation, it seems that replacing spaces with underscores and sending the command line options down as a variable works. E.g:

combined_args="-n ${page_size}k -g ${incache_maxfile}m -y 1k -q 1m -B"
do_test "In_Cache_w/_MMAP" "incache+mmap" $combined_args

results in the desired command line of 
/usr/bin/iozone -az -f /iozone/iozone0/iozone-xfs -n 1024k -g 4096m -y 1k -q 1m -B /iozone/iozone/iozone1

### PR DESCRIPTION
**Pull request by malucius-rh**
Spaces in arguments were messing up how things were passed, making for nonsense iozone command lines. This fixes the space issue for automatic mode in part by converting spaces to underscores and in part by grouping the "test specific" arguments into a variable to be passed down. This also fixes the issue of throughput mode ignoring the difference between --incache, --syncedincache, and --mmapincache.

This closes #29 
This closes #30 

Relates to JIRA: RPOPC-299
Relates to JIRA: RPOPC-300

### CODE REVIEW

**Review by dvalinrh — CHANGES_REQUESTED** [review]
Contact Barry with iozone commands generated.

File: iozone/iozone_run.sh [hunk 1]
```diff
@@ -645,8 +645,8 @@ do_test_actual()
 			else
 				let "file_size=$max_file_size/$4"
 				echo ================================================ >> ${iozone_output_file}
-				echo ${iozone_exe} -t $4 -i ${6} -+n -r ${page_size} -s${file_size}g -e -c -w -C ${iozone_args}-F ${5} >> ${iozone_output_file}
-				time taskset -c 0  ${iozone_exe} -t $4 -i ${6} -+n -r ${page_size} -s${file_size}g -e -c -w -C ${iozone_args} -F ${5} >> ${iozone_output_file}
+				echo ${iozone_exe} -t $4 -i ${6} -+n -r ${page_size} -s${file_size}g -c -w -C ${iozone_args}-F ${5} >> ${iozone_output_file}
```
Comment (frival) [inline iozone/iozone_run.sh:648]: By removing the -e that means you can't count the fsync()/fflush() time in the timing results.  That's not an issue in throughput mode, but I think it'd affect the results in automatic mode.  That change in functionality isn't mentioned in the initial PR comment - is it intentional?

File: iozone/iozone_run.sh [hunk 2]
```diff
@@ -645,8 +645,8 @@ do_test_actual()
...
+				time taskset -c 0  ${iozone_exe} -t $4 -i ${6} -+n -r ${page_size} -s${file_size}g -c -w -C ${iozone_args} -F ${5} >> ${iozone_output_file}
```
Comment (frival) [inline iozone/iozone_run.sh:649]: Let's file an issue to allow changing the taskset behavior here.  I've seen hosts where CPU 0 doesn't exist (weird, I know) and it'd be good if we could support things like moving around among NUMA nodes.  I don't think that needs to be part of this PR but it'd be good functionality to have.

File: iozone/iozone_run.sh [hunk 3]
```diff
@@ -1035,17 +1035,39 @@ execute_iozone()
...
 
-	if [ ${do_incache} -eq 1 ]; then
-		do_test "In Cache" "incache" "-n ${page_size}k -g ${incache_maxfile}m -y 1k -q 1m"
-	fi
-
-	if [ ${do_incache_fsync} -eq 1 ]; then
-		do_test "In Cache + Fsync" "incache+fsync" "-n ${page_size}k -g ${incache_maxfile}m -y 1k -q 1m -e"
-	fi
+	        #Avoid mixing auto flags with throughput mode flags
+        if [[ $auto == 1 ]]; then
```
Comment (frival) [inline iozone/iozone_run.sh:1039]: For consistency, use curly braces around auto.  Sorry I missed that earlier.

File: iozone/iozone_run.sh (hunk 1 above)
Comment (frival) [reply iozone/iozone_run.sh:648]: Never mind, I see where you added it below instead.  Serves me right for commenting inline rather than reviewing in toto and then going back.

**Review by frival — CHANGES_REQUESTED** [review]
One microscopic comment and one issue requested - add the curly braces and I'll LGTM.

File: iozone/iozone_run.sh (hunk 2 above)
Comment (malucius-rh) [reply iozone/iozone_run.sh:649]: ACK

**Comment by malucius-rh** [comment]
> Contact Barry with iozone commands generated.

Met with Barry

**Review by frival — APPROVED** [review]
LGTM

**Review by dvalinrh — APPROVED** [review]
LGTM
